# Generated by Django 2.2 on 2020-10-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_platform', '0003_auto_20201030_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
